//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3Travelin.Resources.Views.Shared.Components._DefaultFooterComponentPartial {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Project3Travelin.Resources.Views.Shared.Components._DefaultFooterComponentPartial" +
                            ".Default_en_US", typeof(Default_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Instagram_dan_Takip_Et {
            get {
                return ResourceManager.GetString("Instagram\'dan Takip Et", resourceCulture);
            }
        }
        
        internal static string Hayalinizdeki_seyahati_gerçeğe_dönüştürmek_için_yola_çıktık__Kültür_turlarından_doğa_kaçamaklarına__yurt_içi_ve_yurt_dışı_rotalarda_unutulmaz_deneyimler_sunuyoruz__Alanında_uzman_rehberlerimiz__güvenli_ulaşım_ve_özenle_planlanmış_programlarımızla_her_detayı_sizin_için_düşünüyoruz_ {
            get {
                return ResourceManager.GetString(@"Hayalinizdeki seyahati gerçeğe dönüştürmek için yola çıktık. Kültür turlarından doğa kaçamaklarına, yurt içi ve yurt dışı rotalarda unutulmaz deneyimler sunuyoruz. Alanında uzman rehberlerimiz, güvenli ulaşım ve özenle planlanmış programlarımızla her detayı sizin için düşünüyoruz.", resourceCulture);
            }
        }
        
        internal static string Hızlı_Linkler {
            get {
                return ResourceManager.GetString("Hızlı Linkler", resourceCulture);
            }
        }
        
        internal static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        internal static string Tur_Listesi {
            get {
                return ResourceManager.GetString("Tur Listesi", resourceCulture);
            }
        }
        
        internal static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        
        internal static string Rezervasyon_Yap {
            get {
                return ResourceManager.GetString("Rezervasyon Yap", resourceCulture);
            }
        }
        
        internal static string Bültenimize_Abone_Olun {
            get {
                return ResourceManager.GetString("Bültenimize Abone Olun", resourceCulture);
            }
        }
        
        internal static string Kampanyalar__yeni_tur_rotaları_ve_özel_indirimlerden_ilk_siz_haberdar_olun_ {
            get {
                return ResourceManager.GetString("Kampanyalar, yeni tur rotaları ve özel indirimlerden ilk siz haberdar olun.", resourceCulture);
            }
        }
        
        internal static string Abone_Ol {
            get {
                return ResourceManager.GetString("Abone Ol", resourceCulture);
            }
        }
        
        internal static string E_posta_Adresiniz {
            get {
                return ResourceManager.GetString("E-posta Adresiniz", resourceCulture);
            }
        }
    }
}
