//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3Travelin.Resources.Views.Shared.Components._DefaultHeaderComponentPartial {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Project3Travelin.Resources.Views.Shared.Components._DefaultHeaderComponentPartial" +
                            ".Default_en_US", typeof(Default_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Başlayan_Fiyatlarla {
            get {
                return ResourceManager.GetString("Başlayan Fiyatlarla", resourceCulture);
            }
        }
        
        internal static string Detay {
            get {
                return ResourceManager.GetString("Detay", resourceCulture);
            }
        }
        
        internal static string Kapasite {
            get {
                return ResourceManager.GetString("Kapasite", resourceCulture);
            }
        }
        
        internal static string kişi {
            get {
                return ResourceManager.GetString("kişi", resourceCulture);
            }
        }
        
        internal static string Önceki {
            get {
                return ResourceManager.GetString("Önceki", resourceCulture);
            }
        }
        
        internal static string Sonraki {
            get {
                return ResourceManager.GetString("Sonraki", resourceCulture);
            }
        }
        
        internal static string Filtrele {
            get {
                return ResourceManager.GetString("Filtrele", resourceCulture);
            }
        }
        
        internal static string Şehir {
            get {
                return ResourceManager.GetString("Şehir", resourceCulture);
            }
        }
        
        internal static string Tüm_Şehirler {
            get {
                return ResourceManager.GetString("Tüm Şehirler", resourceCulture);
            }
        }
        
        internal static string Min_Fiyat {
            get {
                return ResourceManager.GetString("Min Fiyat", resourceCulture);
            }
        }
        
        internal static string Max_Fiyat {
            get {
                return ResourceManager.GetString("Max Fiyat", resourceCulture);
            }
        }
        
        internal static string Toplam {
            get {
                return ResourceManager.GetString("Toplam", resourceCulture);
            }
        }
        
        internal static string Sayfa {
            get {
                return ResourceManager.GetString("Sayfa", resourceCulture);
            }
        }
        
        internal static string tur {
            get {
                return ResourceManager.GetString("tur", resourceCulture);
            }
        }
        
        internal static string İstanbul__Türkiye {
            get {
                return ResourceManager.GetString("İstanbul, Türkiye", resourceCulture);
            }
        }
        
        internal static string Pzrt_Cts_ {
            get {
                return ResourceManager.GetString("Pzrt-Cts:", resourceCulture);
            }
        }
        
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        internal static string Tur_Listesi {
            get {
                return ResourceManager.GetString("Tur Listesi", resourceCulture);
            }
        }
        
        internal static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        
        internal static string Rezervasyon_Yap {
            get {
                return ResourceManager.GetString("Rezervasyon Yap", resourceCulture);
            }
        }
        
        internal static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
    }
}
