//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3Travelin.Resources.Views.Shared.Components._TourVideoComponentPartial {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Project3Travelin.Resources.Views.Shared.Components._TourVideoComponentPartial.Def" +
                            "ault_en_US", typeof(Default_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Gittiğin_Yeri_Sev {
            get {
                return ResourceManager.GetString("Gittiğin Yeri Sev", resourceCulture);
            }
        }
        
        internal static string Hayatını_Keşfet {
            get {
                return ResourceManager.GetString("Hayatını Keşfet", resourceCulture);
            }
        }
        
        internal static string İstediğin_Yere_Seyahat_Et_ {
            get {
                return ResourceManager.GetString("İstediğin Yere Seyahat Et!", resourceCulture);
            }
        }
        
        internal static string Hayatını_Keşfet__Hayalini_Kurduğun_Yerlere_Yolculuk_Yap_ {
            get {
                return ResourceManager.GetString("Hayatını Keşfet, Hayalini Kurduğun Yerlere Yolculuk Yap!", resourceCulture);
            }
        }
    }
}
